/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ogranisationGetOrganisation } from "../funcs/ogranisationGetOrganisation.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Ogranisation extends ClientSDK {
  /**
   * get user org
   */
  async getOrganisation(
    options?: RequestOptions,
  ): Promise<operations.GetOrganisationResponseBody> {
    return unwrapAsync(ogranisationGetOrganisation(
      this,
      options,
    ));
  }
}
