/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Brain } from "./brain.js";
import { Chat } from "./chat.js";
import { Chatbot } from "./chatbot.js";
import { Document } from "./document.js";
import { Integration } from "./integration.js";
import { Ogranisation } from "./ogranisation.js";

export class Acp extends ClientSDK {
  private _brain?: Brain;
  get brain(): Brain {
    return (this._brain ??= new Brain(this._options));
  }

  private _document?: Document;
  get document(): Document {
    return (this._document ??= new Document(this._options));
  }

  private _chat?: Chat;
  get chat(): Chat {
    return (this._chat ??= new Chat(this._options));
  }

  private _chatbot?: Chatbot;
  get chatbot(): Chatbot {
    return (this._chatbot ??= new Chatbot(this._options));
  }

  private _integration?: Integration;
  get integration(): Integration {
    return (this._integration ??= new Integration(this._options));
  }

  private _ogranisation?: Ogranisation;
  get ogranisation(): Ogranisation {
    return (this._ogranisation ??= new Ogranisation(this._options));
  }
}
