workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    acp-OAS:
        inputs:
            - location: ./Athena.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/byteleap-ct0/byteleap/acp-oas
targets:
    acp:
        target: typescript
        source: acp-OAS
        publish:
            npm:
                token: $npm_token
