/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateBrainRequestBody = {
  /**
   * Name of the brain
   */
  name: string;
};

/** @internal */
export const CreateBrainRequestBody$inboundSchema: z.ZodType<
  CreateBrainRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
});

/** @internal */
export type CreateBrainRequestBody$Outbound = {
  name: string;
};

/** @internal */
export const CreateBrainRequestBody$outboundSchema: z.ZodType<
  CreateBrainRequestBody$Outbound,
  z.ZodTypeDef,
  CreateBrainRequestBody
> = z.object({
  name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateBrainRequestBody$ {
  /** @deprecated use `CreateBrainRequestBody$inboundSchema` instead. */
  export const inboundSchema = CreateBrainRequestBody$inboundSchema;
  /** @deprecated use `CreateBrainRequestBody$outboundSchema` instead. */
  export const outboundSchema = CreateBrainRequestBody$outboundSchema;
  /** @deprecated use `CreateBrainRequestBody$Outbound` instead. */
  export type Outbound = CreateBrainRequestBody$Outbound;
}
