/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type CreateChatThreadRequestBody = {
  /**
   * The ID of the brain to associate with the chat
   */
  brainId: string;
  /**
   * The name of the chat
   */
  name: string;
  /**
   * The integration to use for the chat
   */
  integration: string;
};

/** @internal */
export const CreateChatThreadRequestBody$inboundSchema: z.ZodType<
  CreateChatThreadRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  brain_id: z.string(),
  name: z.string(),
  integration: z.string(),
}).transform((v) => {
  return remap$(v, {
    "brain_id": "brainId",
  });
});

/** @internal */
export type CreateChatThreadRequestBody$Outbound = {
  brain_id: string;
  name: string;
  integration: string;
};

/** @internal */
export const CreateChatThreadRequestBody$outboundSchema: z.ZodType<
  CreateChatThreadRequestBody$Outbound,
  z.ZodTypeDef,
  CreateChatThreadRequestBody
> = z.object({
  brainId: z.string(),
  name: z.string(),
  integration: z.string(),
}).transform((v) => {
  return remap$(v, {
    brainId: "brain_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateChatThreadRequestBody$ {
  /** @deprecated use `CreateChatThreadRequestBody$inboundSchema` instead. */
  export const inboundSchema = CreateChatThreadRequestBody$inboundSchema;
  /** @deprecated use `CreateChatThreadRequestBody$outboundSchema` instead. */
  export const outboundSchema = CreateChatThreadRequestBody$outboundSchema;
  /** @deprecated use `CreateChatThreadRequestBody$Outbound` instead. */
  export type Outbound = CreateChatThreadRequestBody$Outbound;
}
