/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteBrainRequest = {
  brainId: string;
};

/** @internal */
export const DeleteBrainRequest$inboundSchema: z.ZodType<
  DeleteBrainRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  brain_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "brain_id": "brainId",
  });
});

/** @internal */
export type DeleteBrainRequest$Outbound = {
  brain_id: string;
};

/** @internal */
export const DeleteBrainRequest$outboundSchema: z.ZodType<
  DeleteBrainRequest$Outbound,
  z.ZodTypeDef,
  DeleteBrainRequest
> = z.object({
  brainId: z.string(),
}).transform((v) => {
  return remap$(v, {
    brainId: "brain_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteBrainRequest$ {
  /** @deprecated use `DeleteBrainRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteBrainRequest$inboundSchema;
  /** @deprecated use `DeleteBrainRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteBrainRequest$outboundSchema;
  /** @deprecated use `DeleteBrainRequest$Outbound` instead. */
  export type Outbound = DeleteBrainRequest$Outbound;
}
