/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type DownloadDocumentRequest = {
  documentId: string;
};

export type DownloadDocumentResponseBody = {
  /**
   * The URL to download the document file. This URL is a pre-signed URL that provides temporary access to the document file hosted on a cloud storage service.
   */
  url?: string | undefined;
};

/** @internal */
export const DownloadDocumentRequest$inboundSchema: z.ZodType<
  DownloadDocumentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  document_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "document_id": "documentId",
  });
});

/** @internal */
export type DownloadDocumentRequest$Outbound = {
  document_id: string;
};

/** @internal */
export const DownloadDocumentRequest$outboundSchema: z.ZodType<
  DownloadDocumentRequest$Outbound,
  z.ZodTypeDef,
  DownloadDocumentRequest
> = z.object({
  documentId: z.string(),
}).transform((v) => {
  return remap$(v, {
    documentId: "document_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DownloadDocumentRequest$ {
  /** @deprecated use `DownloadDocumentRequest$inboundSchema` instead. */
  export const inboundSchema = DownloadDocumentRequest$inboundSchema;
  /** @deprecated use `DownloadDocumentRequest$outboundSchema` instead. */
  export const outboundSchema = DownloadDocumentRequest$outboundSchema;
  /** @deprecated use `DownloadDocumentRequest$Outbound` instead. */
  export type Outbound = DownloadDocumentRequest$Outbound;
}

/** @internal */
export const DownloadDocumentResponseBody$inboundSchema: z.ZodType<
  DownloadDocumentResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string().optional(),
});

/** @internal */
export type DownloadDocumentResponseBody$Outbound = {
  url?: string | undefined;
};

/** @internal */
export const DownloadDocumentResponseBody$outboundSchema: z.ZodType<
  DownloadDocumentResponseBody$Outbound,
  z.ZodTypeDef,
  DownloadDocumentResponseBody
> = z.object({
  url: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DownloadDocumentResponseBody$ {
  /** @deprecated use `DownloadDocumentResponseBody$inboundSchema` instead. */
  export const inboundSchema = DownloadDocumentResponseBody$inboundSchema;
  /** @deprecated use `DownloadDocumentResponseBody$outboundSchema` instead. */
  export const outboundSchema = DownloadDocumentResponseBody$outboundSchema;
  /** @deprecated use `DownloadDocumentResponseBody$Outbound` instead. */
  export type Outbound = DownloadDocumentResponseBody$Outbound;
}
