/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetChatbotListRequest = {
  /**
   * The ID of the brain to filter chatbots
   */
  brainId?: string | undefined;
};

/** @internal */
export const GetChatbotListRequest$inboundSchema: z.ZodType<
  GetChatbotListRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  brain_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "brain_id": "brainId",
  });
});

/** @internal */
export type GetChatbotListRequest$Outbound = {
  brain_id?: string | undefined;
};

/** @internal */
export const GetChatbotListRequest$outboundSchema: z.ZodType<
  GetChatbotListRequest$Outbound,
  z.ZodTypeDef,
  GetChatbotListRequest
> = z.object({
  brainId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    brainId: "brain_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetChatbotListRequest$ {
  /** @deprecated use `GetChatbotListRequest$inboundSchema` instead. */
  export const inboundSchema = GetChatbotListRequest$inboundSchema;
  /** @deprecated use `GetChatbotListRequest$outboundSchema` instead. */
  export const outboundSchema = GetChatbotListRequest$outboundSchema;
  /** @deprecated use `GetChatbotListRequest$Outbound` instead. */
  export type Outbound = GetChatbotListRequest$Outbound;
}
