/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetChatbotGetMessagesRequest = {
  chatbotId?: string | undefined;
};

/** @internal */
export const GetChatbotGetMessagesRequest$inboundSchema: z.ZodType<
  GetChatbotGetMessagesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  chatbot_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "chatbot_id": "chatbotId",
  });
});

/** @internal */
export type GetChatbotGetMessagesRequest$Outbound = {
  chatbot_id?: string | undefined;
};

/** @internal */
export const GetChatbotGetMessagesRequest$outboundSchema: z.ZodType<
  GetChatbotGetMessagesRequest$Outbound,
  z.ZodTypeDef,
  GetChatbotGetMessagesRequest
> = z.object({
  chatbotId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    chatbotId: "chatbot_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetChatbotGetMessagesRequest$ {
  /** @deprecated use `GetChatbotGetMessagesRequest$inboundSchema` instead. */
  export const inboundSchema = GetChatbotGetMessagesRequest$inboundSchema;
  /** @deprecated use `GetChatbotGetMessagesRequest$outboundSchema` instead. */
  export const outboundSchema = GetChatbotGetMessagesRequest$outboundSchema;
  /** @deprecated use `GetChatbotGetMessagesRequest$Outbound` instead. */
  export type Outbound = GetChatbotGetMessagesRequest$Outbound;
}
