/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetChatRequest = {
  chatId: string;
};

/** @internal */
export const GetChatRequest$inboundSchema: z.ZodType<
  GetChatRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  chatId: z.string(),
});

/** @internal */
export type GetChatRequest$Outbound = {
  chatId: string;
};

/** @internal */
export const GetChatRequest$outboundSchema: z.ZodType<
  GetChatRequest$Outbound,
  z.ZodTypeDef,
  GetChatRequest
> = z.object({
  chatId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetChatRequest$ {
  /** @deprecated use `GetChatRequest$inboundSchema` instead. */
  export const inboundSchema = GetChatRequest$inboundSchema;
  /** @deprecated use `GetChatRequest$outboundSchema` instead. */
  export const outboundSchema = GetChatRequest$outboundSchema;
  /** @deprecated use `GetChatRequest$Outbound` instead. */
  export type Outbound = GetChatRequest$Outbound;
}
