/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetChatbotAnalyticsRequest = {
  chatbotId?: string | undefined;
};

/** @internal */
export const GetChatbotAnalyticsRequest$inboundSchema: z.ZodType<
  GetChatbotAnalyticsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  chatbot_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "chatbot_id": "chatbotId",
  });
});

/** @internal */
export type GetChatbotAnalyticsRequest$Outbound = {
  chatbot_id?: string | undefined;
};

/** @internal */
export const GetChatbotAnalyticsRequest$outboundSchema: z.ZodType<
  GetChatbotAnalyticsRequest$Outbound,
  z.ZodTypeDef,
  GetChatbotAnalyticsRequest
> = z.object({
  chatbotId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    chatbotId: "chatbot_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetChatbotAnalyticsRequest$ {
  /** @deprecated use `GetChatbotAnalyticsRequest$inboundSchema` instead. */
  export const inboundSchema = GetChatbotAnalyticsRequest$inboundSchema;
  /** @deprecated use `GetChatbotAnalyticsRequest$outboundSchema` instead. */
  export const outboundSchema = GetChatbotAnalyticsRequest$outboundSchema;
  /** @deprecated use `GetChatbotAnalyticsRequest$Outbound` instead. */
  export type Outbound = GetChatbotAnalyticsRequest$Outbound;
}
