/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetUserMeResponseBody = {
  /**
   * Email ID of the user
   */
  email: string;
  /**
   * Clerk ID of the user
   */
  externalUserId: string;
  /**
   * First name of the user
   */
  firstName: string;
  /**
   * User ID
   */
  id: string;
  /**
   * Last name of the user
   */
  lastName: string;
  /**
   * Phone number of the user
   */
  phoneNumber: string;
};

/** @internal */
export const GetUserMeResponseBody$inboundSchema: z.ZodType<
  GetUserMeResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string(),
  external_user_id: z.string(),
  first_name: z.string(),
  id: z.string(),
  last_name: z.string(),
  phone_number: z.string(),
}).transform((v) => {
  return remap$(v, {
    "external_user_id": "externalUserId",
    "first_name": "firstName",
    "last_name": "lastName",
    "phone_number": "phoneNumber",
  });
});

/** @internal */
export type GetUserMeResponseBody$Outbound = {
  email: string;
  external_user_id: string;
  first_name: string;
  id: string;
  last_name: string;
  phone_number: string;
};

/** @internal */
export const GetUserMeResponseBody$outboundSchema: z.ZodType<
  GetUserMeResponseBody$Outbound,
  z.ZodTypeDef,
  GetUserMeResponseBody
> = z.object({
  email: z.string(),
  externalUserId: z.string(),
  firstName: z.string(),
  id: z.string(),
  lastName: z.string(),
  phoneNumber: z.string(),
}).transform((v) => {
  return remap$(v, {
    externalUserId: "external_user_id",
    firstName: "first_name",
    lastName: "last_name",
    phoneNumber: "phone_number",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUserMeResponseBody$ {
  /** @deprecated use `GetUserMeResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetUserMeResponseBody$inboundSchema;
  /** @deprecated use `GetUserMeResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetUserMeResponseBody$outboundSchema;
  /** @deprecated use `GetUserMeResponseBody$Outbound` instead. */
  export type Outbound = GetUserMeResponseBody$Outbound;
}
