/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type PostChatbotResetRequest = {
  chatbotId?: string | undefined;
};

/** @internal */
export const PostChatbotResetRequest$inboundSchema: z.ZodType<
  PostChatbotResetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  chatbot_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "chatbot_id": "chatbotId",
  });
});

/** @internal */
export type PostChatbotResetRequest$Outbound = {
  chatbot_id?: string | undefined;
};

/** @internal */
export const PostChatbotResetRequest$outboundSchema: z.ZodType<
  PostChatbotResetRequest$Outbound,
  z.ZodTypeDef,
  PostChatbotResetRequest
> = z.object({
  chatbotId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    chatbotId: "chatbot_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostChatbotResetRequest$ {
  /** @deprecated use `PostChatbotResetRequest$inboundSchema` instead. */
  export const inboundSchema = PostChatbotResetRequest$inboundSchema;
  /** @deprecated use `PostChatbotResetRequest$outboundSchema` instead. */
  export const outboundSchema = PostChatbotResetRequest$outboundSchema;
  /** @deprecated use `PostChatbotResetRequest$Outbound` instead. */
  export type Outbound = PostChatbotResetRequest$Outbound;
}
