/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type PostChatbotUpdateRequestBody = {
  /**
   * The id of the chatbot
   */
  chatbotId?: string | undefined;
  /**
   * The name of the chatbot
   */
  name?: string | null | undefined;
  urls?: Array<string> | null | undefined;
};

/** @internal */
export const PostChatbotUpdateRequestBody$inboundSchema: z.ZodType<
  PostChatbotUpdateRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  chatbot_id: z.string().optional(),
  name: z.nullable(z.string()).optional(),
  urls: z.nullable(z.array(z.string())).optional(),
}).transform((v) => {
  return remap$(v, {
    "chatbot_id": "chatbotId",
  });
});

/** @internal */
export type PostChatbotUpdateRequestBody$Outbound = {
  chatbot_id?: string | undefined;
  name?: string | null | undefined;
  urls?: Array<string> | null | undefined;
};

/** @internal */
export const PostChatbotUpdateRequestBody$outboundSchema: z.ZodType<
  PostChatbotUpdateRequestBody$Outbound,
  z.ZodTypeDef,
  PostChatbotUpdateRequestBody
> = z.object({
  chatbotId: z.string().optional(),
  name: z.nullable(z.string()).optional(),
  urls: z.nullable(z.array(z.string())).optional(),
}).transform((v) => {
  return remap$(v, {
    chatbotId: "chatbot_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostChatbotUpdateRequestBody$ {
  /** @deprecated use `PostChatbotUpdateRequestBody$inboundSchema` instead. */
  export const inboundSchema = PostChatbotUpdateRequestBody$inboundSchema;
  /** @deprecated use `PostChatbotUpdateRequestBody$outboundSchema` instead. */
  export const outboundSchema = PostChatbotUpdateRequestBody$outboundSchema;
  /** @deprecated use `PostChatbotUpdateRequestBody$Outbound` instead. */
  export type Outbound = PostChatbotUpdateRequestBody$Outbound;
}
