/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type PostChatbotDeleteRequest = {
  chatbotId?: string | undefined;
};

/** @internal */
export const PostChatbotDeleteRequest$inboundSchema: z.ZodType<
  PostChatbotDeleteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  chatbot_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "chatbot_id": "chatbotId",
  });
});

/** @internal */
export type PostChatbotDeleteRequest$Outbound = {
  chatbot_id?: string | undefined;
};

/** @internal */
export const PostChatbotDeleteRequest$outboundSchema: z.ZodType<
  PostChatbotDeleteRequest$Outbound,
  z.ZodTypeDef,
  PostChatbotDeleteRequest
> = z.object({
  chatbotId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    chatbotId: "chatbot_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostChatbotDeleteRequest$ {
  /** @deprecated use `PostChatbotDeleteRequest$inboundSchema` instead. */
  export const inboundSchema = PostChatbotDeleteRequest$inboundSchema;
  /** @deprecated use `PostChatbotDeleteRequest$outboundSchema` instead. */
  export const outboundSchema = PostChatbotDeleteRequest$outboundSchema;
  /** @deprecated use `PostChatbotDeleteRequest$Outbound` instead. */
  export type Outbound = PostChatbotDeleteRequest$Outbound;
}
