/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type PutTenantAdminUsersUserIdRequestBody = {
  credits: number;
  dailyCredits: number;
};

export type PutTenantAdminUsersUserIdRequest = {
  userId: string;
  requestBody?: PutTenantAdminUsersUserIdRequestBody | undefined;
};

export type PutTenantAdminUsersUserIdResponseBody = {
  message: string;
};

/** @internal */
export const PutTenantAdminUsersUserIdRequestBody$inboundSchema: z.ZodType<
  PutTenantAdminUsersUserIdRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  credits: z.number(),
  daily_credits: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "daily_credits": "dailyCredits",
  });
});

/** @internal */
export type PutTenantAdminUsersUserIdRequestBody$Outbound = {
  credits: number;
  daily_credits: number;
};

/** @internal */
export const PutTenantAdminUsersUserIdRequestBody$outboundSchema: z.ZodType<
  PutTenantAdminUsersUserIdRequestBody$Outbound,
  z.ZodTypeDef,
  PutTenantAdminUsersUserIdRequestBody
> = z.object({
  credits: z.number(),
  dailyCredits: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    dailyCredits: "daily_credits",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutTenantAdminUsersUserIdRequestBody$ {
  /** @deprecated use `PutTenantAdminUsersUserIdRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    PutTenantAdminUsersUserIdRequestBody$inboundSchema;
  /** @deprecated use `PutTenantAdminUsersUserIdRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    PutTenantAdminUsersUserIdRequestBody$outboundSchema;
  /** @deprecated use `PutTenantAdminUsersUserIdRequestBody$Outbound` instead. */
  export type Outbound = PutTenantAdminUsersUserIdRequestBody$Outbound;
}

/** @internal */
export const PutTenantAdminUsersUserIdRequest$inboundSchema: z.ZodType<
  PutTenantAdminUsersUserIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  user_id: z.string(),
  RequestBody: z.lazy(() => PutTenantAdminUsersUserIdRequestBody$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "user_id": "userId",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type PutTenantAdminUsersUserIdRequest$Outbound = {
  user_id: string;
  RequestBody?: PutTenantAdminUsersUserIdRequestBody$Outbound | undefined;
};

/** @internal */
export const PutTenantAdminUsersUserIdRequest$outboundSchema: z.ZodType<
  PutTenantAdminUsersUserIdRequest$Outbound,
  z.ZodTypeDef,
  PutTenantAdminUsersUserIdRequest
> = z.object({
  userId: z.string(),
  requestBody: z.lazy(() => PutTenantAdminUsersUserIdRequestBody$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    userId: "user_id",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutTenantAdminUsersUserIdRequest$ {
  /** @deprecated use `PutTenantAdminUsersUserIdRequest$inboundSchema` instead. */
  export const inboundSchema = PutTenantAdminUsersUserIdRequest$inboundSchema;
  /** @deprecated use `PutTenantAdminUsersUserIdRequest$outboundSchema` instead. */
  export const outboundSchema = PutTenantAdminUsersUserIdRequest$outboundSchema;
  /** @deprecated use `PutTenantAdminUsersUserIdRequest$Outbound` instead. */
  export type Outbound = PutTenantAdminUsersUserIdRequest$Outbound;
}

/** @internal */
export const PutTenantAdminUsersUserIdResponseBody$inboundSchema: z.ZodType<
  PutTenantAdminUsersUserIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

/** @internal */
export type PutTenantAdminUsersUserIdResponseBody$Outbound = {
  message: string;
};

/** @internal */
export const PutTenantAdminUsersUserIdResponseBody$outboundSchema: z.ZodType<
  PutTenantAdminUsersUserIdResponseBody$Outbound,
  z.ZodTypeDef,
  PutTenantAdminUsersUserIdResponseBody
> = z.object({
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutTenantAdminUsersUserIdResponseBody$ {
  /** @deprecated use `PutTenantAdminUsersUserIdResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    PutTenantAdminUsersUserIdResponseBody$inboundSchema;
  /** @deprecated use `PutTenantAdminUsersUserIdResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    PutTenantAdminUsersUserIdResponseBody$outboundSchema;
  /** @deprecated use `PutTenantAdminUsersUserIdResponseBody$Outbound` instead. */
  export type Outbound = PutTenantAdminUsersUserIdResponseBody$Outbound;
}
